language: node_js
sudo: false

env:
  - SENECA_VER=seneca@3.x.x
  - SENECA_VER=seneca@plugin
  - SENECA_VER=senecajs/seneca

node_js:
  - "10"
  - "12"
  - "13"
  - "14"

before_script:
  - npm uninstall seneca
  - npm install $SENECA_VER

after_script:
  - npm run coveralls
